---
vms:
  server:
    count: 2
    role: server
    os: rhel9

serviceAccountName: gitops-vms-sa
rbac:
  roleBindings:
    - name: view-machine-api
      createBinding: true
      scope:
        cluster: false
        namespace: "openshift-machine-api"
      subjects:
        kind: ServiceAccount
        name: gitops-vms-sa
        namespace: gitops-vms
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-machine-api

#waitForMetalNode: false
